build-kvmtool:
  stage: build
  image: gcc:8
  script:
    - git clone https://git.kernel.org/pub/scm/linux/kernel/git/will/kvmtool.git
    - cd kvmtool && make -j$(nproc)
  artifacts:
    untracked: false
    paths:
      - kvmtool/vm
    expire_in: 30 days

build-testhelper:
  stage: build
  image: golang:1.11
  variables:
    CGO_ENABLED: "0"
  script:
    - cd ioctl/testhelper && go build
  artifacts:
    untracked: false
    paths:
      - ioctl/testhelper/testhelper
    expire_in: 30 days

build-ioctl-tests:
  stage: build
  image: golang:1.11
  variables:
    CGO_ENABLED: "0"
  script:
    - cd ioctl && go test -c
  artifacts:
    untracked: false
    paths:
      - ioctl/ioctl.test
    expire_in: 30 days

test:
  stage: test
  image: debian:latest
  variables:
    NEEDS_KVM: "true"
  dependencies:
    - build-kvmtool
    - build-ioctl-tests
    - build-testhelper
  script:
    - apt-get update && apt-get -yy install wget
    - wget -nv -O bzImage https://blob.dolansoft.org/public/gozfs-testenv-linux54
    - kvmtool/vm run -m 256m --kernel bzImage -c1 --console virtio -d ioctl -p "init=/testhelper/testhelper zfs.zfs_flags=512"
    - test -e ioctl/successful || exit 1
  artifacts:
    untracked: false
    when: always
    paths:
      - ioctl/zfsdebug.log
    expire_in: 7 days
